### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by Bandie** [pampanic/pam_panic#2]
We need some people to translate this project.
See [how to translate](https://github.com/pampanic/pam_panic/wiki/How-to-translate)

**Comment by Bandie** [comment]
A review for #87 is required.

**Comment by rhaamo** [comment]
Updated the two fr.po files
[fr_FR.zip](https://github.com/pampanic/pam_panic/files/2569520/fr_FR.zip)

**Comment by Bandie** [comment]
Thank you, @rhaamo :)
